-- AlterTable
ALTER TABLE "Aircraft" ALTER COLUMN "flightHours" SET DEFAULT 0,
ALTER COLUMN "flightHours" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Flight" ALTER COLUMN "duration" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "picTime" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dualTime" SET DATA TYPE DOUBLE PRECISION;
