"use client";

import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Image,
  Font,
} from "@react-pdf/renderer";

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: "#FFFFFF",
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "bold",
    color: "#1a365d",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#2b6cb0",
    paddingBottom: 10,
  },
  headerText: {
    fontSize: 10,
    color: "#4a5568",
  },
  table: {
    display: "flex",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#bf9000",
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: "auto",
    flexDirection: "row",
  },
  tableColHeader: {
    width: "12.5%",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#bf9000",
    borderLeftWidth: 0,
    borderTopWidth: 0,
    backgroundColor: "#fef3c7",
    padding: 5,
  },
  tableCol: {
    width: "12.5%",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#bf9000",
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 5,
  },
  tableCellHeader: {
    fontSize: 8,
    fontWeight: "bold",
  },
  tableCell: {
    fontSize: 8,
  },
  signatureContainer: {
    marginTop: 10,
    alignItems: "center",
  },
  signatureImage: {
    width: 60,
    height: 30,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 8,
    color: "#a0aec0",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 10,
  },
});

interface FlightPDFProps {
  flights: any[];
  userName: string;
}

export const FlightPDF = ({ flights, userName }: FlightPDFProps) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.headerText}>Pilot: {userName}</Text>
            <Text style={styles.headerText}>Report Generated: {new Date().toLocaleDateString()}</Text>
          </View>
          <Text style={styles.title}>Pilot Logbook</Text>
        </View>

        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableRow}>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Date</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Route</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Aircraft</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Hours</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>PIC</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Dual</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Landings</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Verification</Text></View>
          </View>

          {/* Table Rows */}
          {flights.map((f, i) => (
            <View key={i} style={styles.tableRow}>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{new Date(f.date).toLocaleDateString()}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{f.departureCode} - {f.arrivalCode}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{f.aircraft?.registration}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{f.duration}h</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{f.picTime}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{f.dualTime}</Text></View>
              <View style={styles.tableCol}><Text style={styles.tableCell}>{(f.dayLandings || 0) + (f.nightLandings || 0)}</Text></View>
              <View style={styles.tableCol}>
                {f.signatureData ? (
                  <View style={styles.signatureContainer}>
                    <Image src={f.signatureData} style={styles.signatureImage} />
                    <Text style={{ fontSize: 6, marginTop: 2 }}>{f.instructorName}</Text>
                  </View>
                ) : (
                  <Text style={styles.tableCell}>{f.isVerified ? "Verified" : ""}</Text>
                )}
              </View>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by Pilot Handbook - Your Digital Flight Companion. This logbook complies with standard regulatory formats.
        </Text>
      </Page>
    </Document>
  );
};
